apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app.kubernetes.io/part-of: movie-ticket-booking
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/mongo-movie-ticket
    type: DirectoryOrCreate
