services:
  frontend:
    build:
      context: ./Frontend
    container_name: movie-frontend
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - movie-net

  backend:
    build:
      context: ./Backend
    container_name: movie-backend
    ports:
      - '5000:5000'
    env_file:
      - ./Backend/.env
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - movie-net

  mongo:
    image: mongo:7
    container_name: movie-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

    networks:
      - movie-net

volumes:
  mongo-data:

networks:
  movie-net:
    driver: bridge
