apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: movie-ticket
  labels:
    app: frontend
    tier: web
    app.kubernetes.io/part-of: movie-ticket-booking
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
