apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config
  namespace: movie-ticket
  labels:
    app.kubernetes.io/part-of: movie-ticket-booking
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongo-svc.movie-ticket.svc.cluster.local:27017"
  CORS_ORIGIN: "*"
  SENDER_EMAIL: "noreply@movieticket.com"
