# Consider using: kubectl create secret generic movie-secrets --from-env-file=.env -n movie-ticket

apiVersion: v1
kind: Secret
metadata:
  name: movie-secrets
  namespace: movie-ticket
  labels:
    app.kubernetes.io/part-of: movie-ticket-booking
type: Opaque
stringData:
  CLERK_PUBLISHABLE_KEY: ''
  CLERK_SECRET_KEY: ''
  INNGEST_EVENT_KEY: ''
  INNGEST_SIGNING_KEY: ''
  TMDB_API_KEY: ''
  STRIPE_PUBLISHABLE_KEY: ''
  STRIPE_SECRET_KEY: ''
  STRIPE_WEBHOOK_SECRET: ''
  SMTP_USER: ''
  SMTP_PASS_KEY: ''
